---
- hosts: localhost
  become: no
  tasks:
   - name: print ansible facts
     debug:
       msg: >
        The default IPv4 address of {{ ansible_facts.fqdn }}
        is {{ ansible_facts.default_ipv4.address }}
