---
# tasks file for myvhost
- name: install the latest version of Apache
  yum:
    name: "{{ web_pkg }}"
    state: latest

- name: copy apache config
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
  notify: restart httpd

- name: Start service httpd and firewalld
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - "{{ web_svc }}"
    - "{{ fw_svc }}"

- name: configure firewalld
  firewalld:
    service: "{{ rule }}"
    permanent: yes
    immediate: yes
    state: enabled
